#!/usr/bin/env python
import os
import optparse

usage = "usage: %prog [options] existing_cmake_cache.txt config_cache"
parser = optparse.OptionParser(usage=usage)
(opts,args) =parser.parse_args()
if len(args) != 2:
   raise RuntimeError("Must specify input cache and output script name")

prefix = os.getenv('PROTEUS_PREFIX')
proteus = os.getenv('PROTEUS')
with open(args[0],'r') as savedCache, open(args[1],'w') as cmakeCache:
   for line in savedCache:
      newline = line.replace("PROTEUS_PREFIX",prefix)
      newline = line.replace("PROTEUS",proteus)
      cmakeCache.write(newline)
