#!/usr/bin/env python
import os
import optparse

usage = "usage: %prog [options] existing_cmake_cache.txt config_cache"
parser = optparse.OptionParser(usage=usage)
(opts,args) =parser.parse_args()
if len(args) != 2:
   raise RuntimeError("Must specify input cache and output script name")

prefix = os.getenv('PROTEUS_PREFIX')
proteus = os.getenv('PROTEUS')
with open(args[0],'r') as cmakeCache, open(args[1],'w') as savedCache:
   for line in cmakeCache:
      newline = line.replace(prefix,"PROTEUS_PREFIX")
      newline = line.replace(proteus,"PROTEUS")
      savedCache.write(newline)
